### PR TITLE
SWIFT buoys treated as individual platforms.

### PR DESCRIPTION
**Pull request by RobertPincus**
This reorganizes data from the SWIFT drifting buoys to address #62  

At present there are two sources of SWIFT data: `cat.SWIFTNN.track` points to the track data assembled by Bjorn and `cat.swifts.SWIFTNN` points to the complete data including the track, as produced by the data providers. 

This PR adds `cat.SWIFTNN.all` to point to All The Data and removes `cat.swifts.SWIFTNN`. 

I am not convinced, though, that it makes sense to have a `.track` entry with just the track data and `.all` for the complete data, which include the track data. Would it make more sense to simply have `cat.SWIFTNN` point directly to all the data?

### CODE REVIEW

**Comment by RobertPincus** [comment]
@observingClouds I would be curious for your ideas.

**Comment by observingClouds** [comment]
I think this is the best solution for now until we have overcome some of the hierarchical access questions by e.g. specific functions or/and search functionality.

The only issue I still see here is the accessor-name `all`. This is very inclusive and basically questions every other dataset that is already connected with a SWIFT buoy ( `track`) or any additional data that might still come. Can we come up with a different name? My best suggestion is `Level_1`, although it is only a bit more satisfying than `all`, especially because I cannot recall that we have defined what each level means in this community.

**Comment by observingClouds** [comment]
> Would it make more sense to simply have cat.SWIFTNN point directly to all the data?

Not sure, if I understand your question @RobertPincus correctly. Are you proposing to bann the `track` data? I think it will be good on the long run, if we don't have `cat.<thing>` directly point to a dataset, but always have an additional accessor to be able to add further datasets without changing the access structure.

**Review by d70-t — APPROVED** [review]
The change looks fine. But I am with @observingClouds that `all` is probably a bit too inclusive. On the other hand, that is also how the dataset is called in its filename and if that's really all, then why not?

**Pull request merged**
