### PR TITLE
update SMART urls to latest version of files

### PR DESCRIPTION
**Pull request by JuleRadtke**
new files with corrected time shift have been uploaded on Aeris

### CODE REVIEW

**Review by d70-t — COMMENTED** [review]
Looks reasonable, but what's about flights `HALO-0119` and `HALO-0118`?

**Comment by JuleRadtke** [comment]
Ja I wondered about them as well, no updated versions are on aeris for these two. I noted down to ask Kevin about it.

**Comment by d70-t** [comment]
The issue with that situation is that now the format of the dataset returned by
```python
cat.HALO.SMART.spectral_irradiances["HALO-0205"].to_dask()
```
is different from the dataset returned by
```python
cat.HALO.SMART.spectral_irradiances["HALO-0119"].to_dask()
```
which makes using it a lot harder than it should be. I'd think that either there should be additional datasets for the first two flights, or the datasets should be removed from the catalog.

**Comment by JuleRadtke** [comment]
Ja, true. I ask Kevin, if he will upload new versions for the two as well. Until that I delete them from the cataloque.

**Review by d70-t — APPROVED** [review]

**Pull request merged**
