### PR TITLE
change identifiers to official spelling

### PR DESCRIPTION
**Pull request by d70-t**
Most identifier are spelled in upper case according to out metadata
table. This PR changes
* `halo` -> `HALO`
* `p3` -> `P3`
* `bahamas` -> `BAHAMAS`
* `bahamas.ql` -> `BAHAMAS.QL`

### CODE REVIEW

**Comment by RobertPincus** [comment]
So of course the alternative is to change the metadata table. What arguments for or against?

**Comment by d70-t** [comment]
For `HALO`, `BAHAMAS` and `QL` the names are very much established already. For `P3` I can't tell.

**Comment by d70-t** [comment]
One thing which would (but maybe shouldn't) be an argument for `P3` are the `flight_ids` which currently contain `P3` as prefix...

**Review by RobertPincus — APPROVED** [review]
If we consider the meta-data standards to be well-entrenched then this change is quite sensible in promoting uniform naming across the experiment.

**Pull request merged**
