### PR TITLE
initial botany commit

### PR DESCRIPTION
**Pull request by fjansson**
Add catalog entry for botany simulations.

### CODE REVIEW

**Comment by observingClouds** [comment]
Hi @fjansson,
to merge this before intake has been released, could you compress the json file with zip and upload it also to swift? This way we circumvent the current intake bug.
Cheers!

**Comment by fjansson** [comment]
Two more commits: use the zipped json instead of json to get around the intake bug, and added a yaml for the 1536x1536 simulation. So far only the parameter json is there. Then I rebased my branch on top of the new master, hope that went right.
Cheers, 
Fredrik

**Comment by observingClouds** [comment]
This currently depends on solving #102.

**Comment by d70-t** [comment]
Ok, now that #102 is fixed, the test is (correctly) failing as there is currently no implementation for testing the availability of `json` data sources.

* What would be the preferred way of checking if a `json` data source is available?
* Could you add the appropriate check [here](https://github.com/fjansson/eurec4a-intake/blob/403fd32614f2bcf424fae91b7df59715337674d0/tests/test_catalog.py#L46)?

**Comment by observingClouds** [comment]
@fjansson please merge [my PR](https://github.com/fjansson/eurec4a-intake/pull/1) to your branch. It adds a simple test for the `json` data source. It reads the entire data source into memory which is not perfect, but for the json files that we currently have in the catalog this is totally acceptable.

We might change it to `item.discover` when we have resolved the last open points in https://github.com/intake/intake/pull/675

**Comment by fjansson** [comment]
Done. Thanks!

**Review by observingClouds — APPROVED** [review]
This has been a little bit of an effort but now this looks very good. Congratulations everyone who contributed! 🚀 A few changes we made here will make the work also easier in the future.

**Comment by observingClouds** [comment]
Time to work on https://github.com/eurec4a/how_to_eurec4a/pull/81 :smile:

**Pull request merged**
