### PR TITLE
Add ATR isotope data

### PR DESCRIPTION
**Pull request by leonie-villiger**

### CODE REVIEW

**Comment by observingClouds** [comment]
Hi @leonie-villiger,
Thanks for the PR! Great to see more datasets joining! 🥳  I committed a few changes to match the structure of the other airplane data. I think what is now left to do is:

- [ ] add the additional flight days in [ATR/isotope-analyzer-CRDS.yaml](https://github.com/leonie-villiger/eurec4a-intake/blob/master/ATR/isotope-analyzer-CRDS.yaml) (@leonie-villiger could you do this?)
- [ ] check if I used the correct instrument name (@leonie-villiger was it an CRDS on the ATR?) to match the syntax discussed in [#153](https://github.com/eurec4a/eurec4a-intake/pull/153#discussion_r1404675272)
- [ ] discuss how the metadata/flight segment data should be added
I removed your [initial indexing of the metadata](https://github.com/eurec4a/eurec4a-intake/blob/631282fe465908a7cb23dc5af4f0e34713047702/ATR/isotopes.yaml#L16-L24) because I realised that this metadata is following the flight segmentation syntax. I added the url to the metadata for now [as an argument to the datasets metadata](https://github.com/leonie-villiger/eurec4a-intake/blob/39664b6e548bed0566e515da1f3cd50951a2a459/ATR/isotope-analyzer-CRDS.yaml#L17). However, I think we want to add this metadata to the [flight-segmentation repository](https://github.com/eurec4a/flight-phase-separation/tree/master). Could the experts @Smpljack, @d70-t, @leifdenby comment on this and help us eventually on-board the yaml-files in https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/?

**Comment by Smpljack** [comment]
Hi @leonie-villiger and @observingClouds ,
it has been some time for me to be involved in flight-segmentation issues, so let me know if I am following along well. I understand that Hauke's question basically is whether the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/) should be integrated to the [flight-phase-separation](https://github.com/eurec4a/flight-phase-separation) repo, correct? 

This would seem consistent from my point of view, the format mostly accommodates the HALO/P3 standards already (On first sight, I see that we call the segment kind rather "kinds" and allow several entries...). A small readme could be added to explain new types of segment kinds in the style of [`P3-segmentation-notes.md`](https://github.com/eurec4a/flight-phase-separation/blob/master/P3-segmentation-notes.md).

Then there are additional isotope meta data files [(isotope-analyzer-CRDS.yaml)](https://github.com/leonie-villiger/eurec4a-intake/blob/master/ATR/isotope-analyzer-CRDS.yaml). I understand that these should be kept independent of the flight segment files since they contain a lot of arguments that don't contain flight segment information. Maybe the `description` argument could be added to the remarks for each flight of the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/).

How about opening a PR to the [flight-phase-separation](https://github.com/eurec4a/flight-phase-separation) repo with the addition of the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/) to iterate on the details?

**Comment by observingClouds** [comment]
@Smpljack thanks for your response! This is already very helpful.

>I understand that Hauke's question basically is whether the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/) should be integrated to the [flight-phase-separation](https://github.com/eurec4a/flight-phase-separation) repo, correct?

Correct!

> This would seem consistent from my point of view, the format mostly accommodates the HALO/P3 standards already (On first sight, I see that we call the segment kind rather "kinds" and allow several entries...). A small readme could be added to explain new types of segment kinds in the style of [P3-segmentation-notes.md](https://github.com/eurec4a/flight-phase-separation/blob/master/P3-segmentation-notes.md).

Ah, the `kind` <> `kinds` is a shame, but lets talk about this and the addition of new definitions over in the flight-segmentation repo.

> Then there are additional isotope meta data files [(isotope-analyzer-CRDS.yaml)](https://github.com/leonie-villiger/eurec4a-intake/blob/master/ATR/isotope-analyzer-CRDS.yaml). I understand that these should be kept independent of the flight segment files since they contain a lot of arguments that don't contain flight segment information. Maybe the description argument could be added to the remarks for each flight of the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/).

The  [(isotope-analyzer-CRDS.yaml)](https://github.com/leonie-villiger/eurec4a-intake/blob/master/ATR/isotope-analyzer-CRDS.yaml) is currently only referencing the [ATR metadata files](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/). Because these ATR metadata files are (almost) flight segmentation files, they seem to be of much better use if they are handled like that, i.e. be accessible through the flight-segmentation "API"

**Comment by leonie-villiger** [comment]
@observingClouds: 

I added the additional flights in [ATR/isotope-analyzer-CRDS.yaml](https://github.com/leonie-villiger/eurec4a-intake/blob/master/ATR/isotope-analyzer-CRDS.yaml). Had to add the flight number to the identifier, because we sometimes had two flights on one day (`ATR-0125` now reads `ATR-0125-02`).

Yes, it was a CRDS instrument on the ATR. All correct! 

About the metadata: There are two types of metadata:
1. [ATR metadata files (isotopes)](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/vapour/) belonging to the isotope measurements, currently referenced in the [ATR/isotope-analyzer-CRDS.yaml](https://github.com/leonie-villiger/eurec4a-intake/blob/master/ATR/isotope-analyzer-CRDS.yaml) as `note`. This metadata is only relevant for the isotope data from the ATR.
2. [ATR metadata files (flight segments)](https://observations.ipsl.fr/aeris/eurec4a-data/AIRCRAFT/ATR/YAML-ATR/). This is the official flight segmentation for all the ATR data (see [description](https://doi.org/10.25326/315)).

I assume it is rather number 2 which you want to include in the [flight-phase-separation](https://github.com/eurec4a/flight-phase-separation) repository.

**Review by observingClouds — APPROVED** [review]

**Comment by observingClouds** [comment]
The integration of ATR flight segments is discussed at https://github.com/eurec4a/flight-phase-separation/issues/32

**Pull request merged**
