### PR TITLE
Update default version of RV-Meteor LIMRAD94 radar data

### LINKED ISSUE #156: Update RV Meteor cloud radar dataset
Hi @jroettenbacher,

I just came across an older message on mattermost about version 1.2 of the Meteor cloud radar update. Could you please update this entry here as well so we are up-to-date?

Thanks!

### PR DESCRIPTION
**Pull request by jroettenbacher**
Closes #156

### CODE REVIEW

**Review by observingClouds — COMMENTED** [review]
Awesome! Could you also add a line to the CHANGELOG.md?

**Comment by observingClouds** [comment]
You could reset your last two commits and force push them. Normally reseting is not nice as it rewrites the history, but in a PR it is acceptable. I can also just sqash your PR as there is little information in each commit. Just let me know

**Comment by jroettenbacher** [comment]
Alright done! This should be mergable now

**Review by observingClouds — APPROVED** [review]
Awesome! This looks great now. Thanks @jroettenbacher

**Pull request merged**
